# Site settings
title: Barebook Design System
description: "A mini design system with a strong focus on performance, scalability, maintainability, and a small footprint."
keywords:
name: Barebook
short_name:
image: /assets/images/site-image.jpg
url: https://barebook.gm/
type: website
lang: "en-GB"

author: A Camariana
author_site: https://camariana.gm/
author_github: https://github.com/camariana/

# Global Configuration
source: src
timezone: Africa/Banjul

# Build Command Options
#baseurl:

# Serve Command OptionsPermalink
#port: 40003
livereload: true
open_url: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Sass Settings
sass:
  add_charset: true
  sass_dir: _sass
  style: :compressed

# Collections Settings
collections_dir: my_collections
collections:
  elements:
    output: false
  components:
    output: true
  patterns:
    output: true
  build-with:
    output: false

# Links
barebook_code: https://github.com/camariana/barebook